image: node:18.16.0
variables:
  SOFT_VERSION: $SOFT_VERSION
  DOCK_HUB: 10.10.11.145:8082
  DOCK_HUB_USER: admin
  DOCK_HUB_PASSWD: 'gqYXy2cPEAgAJ8W'
  HUB_GROUP_PASSWD: 1234QWERasdf
  LAY_OUT_URL: ${DOCK_HUB}/phishing-system
  SSH_PASSWORD: Zzz.1997
  SSH_USERNAME: zhouchengfei

stages:
  - build
  - deploy
# 缓存
cache:
  paths:
    - node_modules

before_script:
  # npm install的依赖配置
  - git config --global url."https://".insteadOf git://
  - docker login -u ${DOCK_HUB_USER} -p${DOCK_HUB_PASSWD} http://${DOCK_HUB}
  # TAG版本号
  - export TM=`date +%y%m%d%H%M`
  - export TAG="${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA:0:8}-build${CI_PIPELINE_ID}-${SOFT_VERSION}"

# 打包微服务镜像
build:
  stage: build
  tags:
    - baler
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      when: manual
    - if: $CI_COMMIT_BRANCH == "release" && $CI_PIPELINE_SOURCE == "schedule"
      when: on_success
  script:
    - docker build --force-rm -t ${LAY_OUT_URL}/phishing-view:${TAG} -f ./Dockerfile .
    - docker push ${LAY_OUT_URL}/phishing-view:${TAG}
    - docker rmi ${LAY_OUT_URL}/phishing-view:${TAG}
    
deploy:
  stage: deploy
  tags:
    - baler
  script:
    # 使用SSH连接到目标服务器
    - sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USERNAME@172.16.20.30 \
      'cd Document/docker/phishing/phising-view && \
      docker-compose down && \
      sed -i "s|image:.*|image: ${LAY_OUT_URL}/phishing-view:${TAG}|g" docker-compose.yml && \
      docker-compose up -d'